server:
  port: 8082

spring:
  application:
    name: balance-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    enabled: true
    locations: classpath:db/
    baseline-on-migrate: true
    validate-on-migrate: true
  datasource:
    url: jdbc:postgresql://balance-postgres:5432/balance_db
    username: balance_user
    password: balance_password
    driver-class-name: org.postgresql.Driver
  jackson:
    deserialization:
      USE_BIG_DECIMAL_FOR_FLOATS: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    redis:
      host: redis
      port: 6379
      database: 0  # База для балансов


  # JPA настройки
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false

# Actuator настройки
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,mappings,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    env:
      enabled: true
    mappings:
      enabled: true
    configprops:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Логирование для Docker
logging:
  level:
    com.dbo: INFO
    org.springframework.web: INFO
    org.hibernate: WARN
    org.apache.kafka: WARN

# Кастомные настройки
app:
  environment: DOCKER
  payment:
    max-amount: 1000000
    processing-timeout: 30s
  kafka:
    topics:
      payment-requests: payment-requests
      balance-updates: balance-updates
      payment-status: payment-status

# Настройки Swagger UI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
  api-docs:
    path: /api-docs